on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.15.0'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install
      run: |
        npm install

    - name: npm test
      run: |
        npm run test:unit

    - name: npm lint
      run: |
        npm run lint

    - name: npm build
      run: |
        npm run build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: ./dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./dist

    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to the server
      run: |
        rsync -a -r --progress --human-readable --delete \
        . root@82.148.16.149:/var/www/html/
